# Chemins vers les fichiers
paths:
  raw_data_1: data/raw/client_train.csv
  raw_data_2: data/raw/invoice_train.zip
  test_data_1: data/raw/client_test.csv
  test_data_2: data/raw/invoice_test.zip
  processed_data: data/processed/df_client_train_final.csv
  model_dir: models/

# Colonnes
columns:
  target: target
  id: customer_id
  datetime: timestamp
  features:
    - meter_reading
    - location
    - meter_type
    - region
    - customer_type
    - days_since_last_reading
    - average_daily_consumption

# Modèle
model:
  name: xgboost
  params:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 6
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

# Entraînement
training:
  test_size: 0.2
  random_state: 42
  cv_folds: 5
  scoring: roc_auc

# Encodage
encoding:
  categorical_cols:
    - location
    - meter_type
    - region
    - customer_type
  encoding_strategy: onehot

# Normalisation
scaling:
  numerical_cols:
    - meter_reading
    - days_since_last_reading
    - average_daily_consumption
  method: standard